### ISSUE TITLE
Заполнение README.md

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/utp2020-6-chat#1]
Необходимо заполнить `README.md` — дать нормальное имя проекту, краткое описание и список участников с никами.

* [x] Нужно вместо **upt2020-6-chat** придумать и написать нормальное название.
* [x] Добавить краткое описание — один-два предложения.
* [x] Написать список участников со ссылками на профили.
* [x] Написать инструкцию по запуску приложения.

**Comment by Mazdaywik** [comment]
Не зачту никому из вашей команды УТП, пока вы не заполните `README.md`.

**Comment by Mazdaywik** [comment]
В README список участников неправильно отображается. Поправьте, пожалуйста, разметку.

**Comment by MuonSevasch** [comment]
Исправил 06.10.2020, 16:34, "Alexander Konovalov" <notifications@github.com>:
В README список участников неправильно отображается. Поправьте, пожалуйста, разметку.

**Comment by Mazdaywik** [comment]
Стало лучше, нужен ещё один шаг:
![image](https://user-images.githubusercontent.com/1309859/95225823-dfa5ab80-0804-11eb-8cc1-aea2a85ba4b4.png)
Добавьте маркированный список:
```Markdown
* раз
* два
* три
```
* раз
* два
* три

**Comment by MuonSevasch** [comment]
готово18:51, 6 октября 2020 г., Alexander Konovalov <notifications@github.com>:
Стало лучше, нужен ещё один шаг:

Добавьте маркированный список:
* раз
* два
* три

раз
два
три


—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by MuonSevasch** [comment]
не подскажите, во сколько можно будет подойти? 20:40, 6 октября 2020 г., MuonSevasch <muon.kvark@yandex.ru>:готово18:51, 6 октября 2020 г., Alexander Konovalov <notifications@github.com>:
Стало лучше, нужен ещё один шаг:

Добавьте маркированный список:
* раз
* два
* три

раз
два
три


—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by Mazdaywik** [comment]
> не подскажите, во сколько можно будет подойти? 20:40, 6 октября 2020 г., MuonSevasch 

Сегодня можно. Вы уже подошли и получили «отлично». Но закрыть issue нужно с комментарием во имя вселенского бюрократизма.
